[GLOBAL]
pants_version = "2.29.1"
backend_packages = [
    'pants.backend.python',
]

[source]
# Folder(s) containing top-level Python modules.
# See https://www.pantsbuild.org/docs/source-roots
root_patterns = ['/']

[python]
interpreter_constraints = ['CPython>=3.10']
